import '../model/model.dart';
import 'package:flutter/cupertino.dart';

class MealProvider with ChangeNotifier {
  List<Meal> _items = [
    Meal(
      id: 'm1',
      categories: [
        'c1',
      ],
      title: 'Roast Raan',
      affordability: Affordability.Affordable,
      complexity: Complexity.Simple,
      imageUrl: 'https://i.dawn.com/primary/2018/09/5b89e0973731f.jpg',
      duration: 20,
      ingredients: [
        '4 Tomatoes',
        '1 Tablespoon of Olive Oil',
        '1 Onion',
        '250g Spaghetti',
        'Spices',
        'Cheese (optional)'
      ],
      steps: [
        'Cut the tomatoes and the onion into small pieces.',
        'Boil some water - add salt to it once it boils.',
        'Put the spaghetti into the boiling water - they should be done in about 10 to 12 minutes.',
        'In the meantime, heaten up some olive oil and add the cut onion.',
        'After 2 minutes, add the tomato pieces, salt, pepper and your other spices.',
        'The sauce will be done once the spaghetti are.',
        'Feel free to add some cheese on top of the finished dish.'
      ],
      isGlutenFree: false,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm2',
      categories: [
        'c1',
      ],
      title: 'Mughli Steam Roast',
      affordability: Affordability.Affordable,
      complexity: Complexity.Simple,
      imageUrl:
          'https://media.plateaway.com/wp-content/uploads/2020/10/10231333/025A3554-scaled-e1603222917397-405x330.jpg',
      duration: 10,
      ingredients: [
        '1 Slice White Bread',
        '1 Slice Ham',
        '1 Slice Pineapple',
        '1-2 Slices of Cheese',
        'Butter'
      ],
      steps: [
        'Butter one side of the white bread',
        'Layer ham, the pineapple and cheese on the white bread',
        'Bake the toast for round about 10 minutes in the oven at 200°C'
      ],
      isGlutenFree: false,
      isVegan: false,
      isVegetarian: false,
      isLactoseFree: false,
    ),
    Meal(
      id: 'm3',
      categories: [
        'c1',
      ],
      title: 'Patiala',
      affordability: Affordability.Pricey,
      complexity: Complexity.Simple,
      imageUrl: 'https://i.ytimg.com/vi/3Hb2vYCoVTA/maxresdefault.jpg',
      duration: 45,
      ingredients: [
        '300g Cattle Hack',
        '1 Tomato',
        '1 Cucumber',
        '1 Onion',
        'Ketchup',
        '2 Burger Buns'
      ],
      steps: [
        'Form 2 patties',
        'Fry the patties for c. 4 minutes on each side',
        'Quickly fry the buns for c. 1 minute on each side',
        'Bruch buns with ketchup',
        'Serve burger with tomato, cucumber and onion'
      ],
      isGlutenFree: false,
      isVegan: false,
      isVegetarian: false,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm4',
      categories: [
        'c1',
      ],
      title: 'Rani Chaap',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Challenging,
      imageUrl:
          'https://i.pinimg.com/564x/1b/48/e7/1b48e73b8ccac39e18570d8f6e9e42fd.jpg',
      duration: 60,
      ingredients: [
        '8 Veal Cutlets',
        '4 Eggs',
        '200g Bread Crumbs',
        '100g Flour',
        '300ml Butter',
        '100g Vegetable Oil',
        'Salt',
        'Lemon Slices'
      ],
      steps: [
        'Tenderize the veal to about 2–4mm, and salt on both sides.',
        'On a flat plate, stir the eggs briefly with a fork.',
        'Lightly coat the cutlets in flour then dip into the egg, and finally, coat in breadcrumbs.',
        'Heat the butter and oil in a large pan (allow the fat to get very hot) and fry the schnitzels until golden brown on both sides.',
        'Make sure to toss the pan regularly so that the schnitzels are surrounded by oil and the crumbing becomes ‘fluffy’.',
        'Remove, and drain on kitchen paper. Fry the parsley in the remaining oil and drain.',
        'Place the schnitzels on awarmed plate and serve garnishedwith parsley and slices of lemon.'
      ],
      isGlutenFree: false,
      isVegan: false,
      isVegetarian: false,
      isLactoseFree: false,
    ),
    Meal(
      id: 'm5',
      categories: [
        'c1',
      ],
      title: 'Chikken Raishmi tikka',
      affordability: Affordability.Affordable,
      complexity: Complexity.Hard,
      imageUrl:
          'https://www.thespruceeats.com/thmb/EueHyKtddggqkU2N4fpHFVhCfgQ=/2812x1582/smart/filters:no_upscale()/Indian-chicken-kebab-GettyImages-91279048-58eee4623df78cd3fcd0c6ca.jpg',
      duration: 240,
      ingredients: [
        '4 Sheets of Gelatine',
        '150ml Orange Juice',
        '80g Sugar',
        '300g Yoghurt',
        '200g Cream',
        'Orange Peel',
      ],
      steps: [
        'Dissolve gelatine in pot',
        'Add orange juice and sugar',
        'Take pot off the stove',
        'Add 2 tablespoons of yoghurt',
        'Stir gelatin under remaining yoghurt',
        'Cool everything down in the refrigerator',
        'Whip the cream and lift it under die orange mass',
        'Cool down again for at least 4 hours',
        'Serve with orange peel',
      ],
      isGlutenFree: true,
      isVegan: false,
      isVegetarian: true,
      isLactoseFree: false,
    ),
    Meal(
      id: 'm6',
      categories: [
        'c1',
      ],
      title: 'Chikken Tikka',
      affordability: Affordability.Affordable,
      complexity: Complexity.Hard,
      imageUrl: 'https://i.ytimg.com/vi/3n87Tbu5A9M/maxresdefault.jpg',
      duration: 240,
      ingredients: [
        '4 Sheets of Gelatine',
        '150ml Orange Juice',
        '80g Sugar',
        '300g Yoghurt',
        '200g Cream',
        'Orange Peel',
      ],
      steps: [
        'Dissolve gelatine in pot',
        'Add orange juice and sugar',
        'Take pot off the stove',
        'Add 2 tablespoons of yoghurt',
        'Stir gelatin under remaining yoghurt',
        'Cool everything down in the refrigerator',
        'Whip the cream and lift it under die orange mass',
        'Cool down again for at least 4 hours',
        'Serve with orange peel',
      ],
      isGlutenFree: true,
      isVegan: false,
      isVegetarian: true,
      isLactoseFree: false,
    ),
    Meal(
      id: 'm7',
      categories: [
        'c1',
      ],
      title: ' Chiken Tikka',
      affordability: Affordability.Affordable,
      complexity: Complexity.Simple,
      imageUrl:
          'https://i.pinimg.com/originals/d3/2d/d6/d32dd6b612250e31924e35a6aeeca436.jpg',
      duration: 20,
      ingredients: [
        '1 1/2 Cups all-purpose Flour',
        '3 1/2 Teaspoons Baking Powder',
        '1 Teaspoon Salt',
        '1 Tablespoon White Sugar',
        '1 1/4 cups Milk',
        '1 Egg',
        '3 Tablespoons Butter, melted',
      ],
      steps: [
        'In a large bowl, sift together the flour, baking powder, salt and sugar.',
        'Make a well in the center and pour in the milk, egg and melted butter; mix until smooth.',
        'Heat a lightly oiled griddle or frying pan over medium high heat.',
        'Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake. Brown on both sides and serve hot.'
      ],
      isGlutenFree: true,
      isVegan: false,
      isVegetarian: true,
      isLactoseFree: false,
    ),
    Meal(
      id: 'm8',
      categories: [
        'c1',
      ],
      title: 'Irani Tikka',
      affordability: Affordability.Pricey,
      complexity: Complexity.Challenging,
      imageUrl:
          'https://image.shutterstock.com/image-photo/tikka-boti5-260nw-223265578.jpg',
      duration: 35,
      ingredients: [
        '4 Chicken Breasts',
        '1 Onion',
        '2 Cloves of Garlic',
        '1 Piece of Ginger',
        '4 Tablespoons Almonds',
        '1 Teaspoon Cayenne Pepper',
        '500ml Coconut Milk',
      ],
      steps: [
        'Slice and fry the chicken breast',
        'Process onion, garlic and ginger into paste and sauté everything',
        'Add spices and stir fry',
        'Add chicken breast + 250ml of water and cook everything for 10 minutes',
        'Add coconut milk',
        'Serve with rice'
      ],
      isGlutenFree: true,
      isVegan: false,
      isVegetarian: false,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm9',
      categories: [
        'c1',
      ],
      title: 'Tandori Kabab',
      affordability: Affordability.Affordable,
      complexity: Complexity.Hard,
      imageUrl:
          'https://www.pakladies.com/wp-content/uploads/2017/02/Tandoori-Seekh-Kabab-Recipe.jpg',
      duration: 45,
      ingredients: [
        '1 Teaspoon melted Butter',
        '2 Tablespoons white Sugar',
        '2 Ounces 70% dark Chocolate, broken into pieces',
        '1 Tablespoon Butter',
        '1 Tablespoon all-purpose Flour',
        '4 1/3 tablespoons cold Milk',
        '1 Pinch Salt',
        '1 Pinch Cayenne Pepper',
        '1 Large Egg Yolk',
        '2 Large Egg Whites',
        '1 Pinch Cream of Tartar',
        '1 Tablespoon white Sugar',
      ],
      steps: [
        'Preheat oven to 190°C. Line a rimmed baking sheet with parchment paper.',
        'Brush bottom and sides of 2 ramekins lightly with 1 teaspoon melted butter; cover bottom and sides right up to the rim.',
        'Add 1 tablespoon white sugar to ramekins. Rotate ramekins until sugar coats all surfaces.',
        'Place chocolate pieces in a metal mixing bowl.',
        'Place bowl over a pan of about 3 cups hot water over low heat.',
        'Melt 1 tablespoon butter in a skillet over medium heat. Sprinkle in flour. Whisk until flour is incorporated into butter and mixture thickens.',
        'Whisk in cold milk until mixture becomes smooth and thickens. Transfer mixture to bowl with melted chocolate.',
        'Add salt and cayenne pepper. Mix together thoroughly. Add egg yolk and mix to combine.',
        'Leave bowl above the hot (not simmering) water to keep chocolate warm while you whip the egg whites.',
        'Place 2 egg whites in a mixing bowl; add cream of tartar. Whisk until mixture begins to thicken and a drizzle from the whisk stays on the surface about 1 second before disappearing into the mix.',
        'Add 1/3 of sugar and whisk in. Whisk in a bit more sugar about 15 seconds.',
        'whisk in the rest of the sugar. Continue whisking until mixture is about as thick as shaving cream and holds soft peaks, 3 to 5 minutes.',
        'Transfer a little less than half of egg whites to chocolate.',
        'Mix until egg whites are thoroughly incorporated into the chocolate.',
        'Add the rest of the egg whites; gently fold into the chocolate with a spatula, lifting from the bottom and folding over.',
        'Stop mixing after the egg white disappears. Divide mixture between 2 prepared ramekins. Place ramekins on prepared baking sheet.',
        'Bake in preheated oven until scuffles are puffed and have risen above the top of the rims, 12 to 15 minutes.',
      ],
      isGlutenFree: true,
      isVegan: false,
      isVegetarian: true,
      isLactoseFree: false,
    ),
    Meal(
      id: 'm10',
      categories: [
        'c1',
      ],
      title: 'Fried Chicken Wings',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://c.ndtvimg.com/2019-05/usn4dnv_fried-chicken_625x300_24_May_19.jpg',
      duration: 30,
      ingredients: [
        'White and Green Asparagus',
        '30g Pine Nuts',
        '300g Cherry Tomatoes',
        'Salad',
        'Salt, Pepper and Olive Oil'
      ],
      steps: [
        'Wash, peel and cut the asparagus',
        'Cook in salted water',
        'Salt and pepper the asparagus',
        'Roast the pine nuts',
        'Halve the tomatoes',
        'Mix with asparagus, salad and dressing',
        'Serve with Baguette'
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm11',
      categories: [
        'c1',
      ],
      title: 'Punjabi Masla Chicken',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://www.thegheespot.net/wp-content/uploads/2020/08/Masala-Chicken-Wings-1.jpg?v=1609896629',
      duration: 30,
      ingredients: [
        'White and Green Asparagus',
        '30g Pine Nuts',
        '300g Cherry Tomatoes',
        'Salad',
        'Salt, Pepper and Olive Oil'
      ],
      steps: [
        'Wash, peel and cut the asparagus',
        'Cook in salted water',
        'Salt and pepper the asparagus',
        'Roast the pine nuts',
        'Halve the tomatoes',
        'Mix with asparagus, salad and dressing',
        'Serve with Baguette'
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm1',
      categories: [
        'c2',
      ],
      title: 'Chinees Ghoobi Ghost ',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://cdn.shortpixel.ai/spai/w_1038+q_lossless+ret_img+to_webp/https://funcooking.co.uk/wp-content/uploads/2015/11/Gobi-gosht-224.jpg',
      duration: 30,
      ingredients: [
        'White and Green Asparagus',
        '30g Pine Nuts',
        '300g Cherry Tomatoes',
        'Salad',
        'Salt, Pepper and Olive Oil'
      ],
      steps: [
        'Wash, peel and cut the asparagus',
        'Cook in salted water',
        'Salt and pepper the asparagus',
        'Roast the pine nuts',
        'Halve the tomatoes',
        'Mix with asparagus, salad and dressing',
        'Serve with Baguette'
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm2',
      categories: [
        'c2',
      ],
      title: 'Amritsari Dal Gosht',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'http://www.pakistanichefrecipes.com/wp-content/uploads/2019/06/dal-mutton-500x500.jpg',
      duration: 30,
      ingredients: [
        'White and Green Asparagus',
        '30g Pine Nuts',
        '300g Cherry Tomatoes',
        'Salad',
        'Salt, Pepper and Olive Oil'
      ],
      steps: [
        'Wash, peel and cut the asparagus',
        'Cook in salted water',
        'Salt and pepper the asparagus',
        'Roast the pine nuts',
        'Halve the tomatoes',
        'Mix with asparagus, salad and dressing',
        'Serve with Baguette'
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm3',
      categories: [
        'c2',
      ],
      title: 'Lahori Beef Sticks',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://i.pinimg.com/originals/56/c6/88/56c6881f1a4e308f8511294787faa6e2.jpg',
      duration: 30,
      ingredients: [
        'White and Green Asparagus',
        '30g Pine Nuts',
        '300g Cherry Tomatoes',
        'Salad',
        'Salt, Pepper and Olive Oil'
      ],
      steps: [
        'Wash, peel and cut the asparagus',
        'Cook in salted water',
        'Salt and pepper the asparagus',
        'Roast the pine nuts',
        'Halve the tomatoes',
        'Mix with asparagus, salad and dressing',
        'Serve with Baguette'
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm4',
      categories: [
        'c2',
      ],
      title: 'Beef korma Akbri',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://www.sooperchef.pk/uploads/topics/2020/11/chicken-korma-recipe-550x375.jpg',
      duration: 30,
      ingredients: [
        'White and Green Asparagus',
        '30g Pine Nuts',
        '300g Cherry Tomatoes',
        'Salad',
        'Salt, Pepper and Olive Oil'
      ],
      steps: [
        'Wash, peel and cut the asparagus',
        'Cook in salted water',
        'Salt and pepper the asparagus',
        'Roast the pine nuts',
        'Halve the tomatoes',
        'Mix with asparagus, salad and dressing',
        'Serve with Baguette'
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm5',
      categories: [
        'c2',
      ],
      title: 'Muhabat Khaani Pasanday',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://photo-cdn.urdupoint.com/show_img_new/cooking/cooking_images/570x400/pic_85124_1502098112.jpg._3',
      duration: 30,
      ingredients: [
        'White and Green Asparagus',
        '30g Pine Nuts',
        '300g Cherry Tomatoes',
        'Salad',
        'Salt, Pepper and Olive Oil'
      ],
      steps: [
        'Wash, peel and cut the asparagus',
        'Cook in salted water',
        'Salt and pepper the asparagus',
        'Roast the pine nuts',
        'Halve the tomatoes',
        'Mix with asparagus, salad and dressing',
        'Serve with Baguette'
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm6',
      categories: [
        'c2',
      ],
      title: 'Kofte ka Salan',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://www.chilitochoc.com/wp-content/uploads/2020/03/koftacurry3-e1595187971189.jpg',
      duration: 30,
      ingredients: [
        'White and Green Asparagus',
        '30g Pine Nuts',
        '300g Cherry Tomatoes',
        'Salad',
        'Salt, Pepper and Olive Oil'
      ],
      steps: [
        'Wash, peel and cut the asparagus',
        'Cook in salted water',
        'Salt and pepper the asparagus',
        'Roast the pine nuts',
        'Halve the tomatoes',
        'Mix with asparagus, salad and dressing',
        'Serve with Baguette'
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm7',
      categories: [
        'c2',
      ],
      title: 'Beef karahi',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://recipesinurdu.com/wp-content/uploads/2020/07/beef-karahi-1.jpg',
      duration: 30,
      ingredients: [
        'White and Green Asparagus',
        '30g Pine Nuts',
        '300g Cherry Tomatoes',
        'Salad',
        'Salt, Pepper and Olive Oil'
      ],
      steps: [
        'Wash, peel and cut the asparagus',
        'Cook in salted water',
        'Salt and pepper the asparagus',
        'Roast the pine nuts',
        'Halve the tomatoes',
        'Mix with asparagus, salad and dressing',
        'Serve with Baguette'
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),

    // Chicken Recipe
    Meal(
      id: 'm1',
      categories: [
        'c3',
      ],
      title: 'Mutter Chiken Chaap',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://i0.wp.com/www.funloveandcooking.com/wp-content/uploads/2015/07/Lamb-Chops-Recipe-FunLoveAndCooking.com_.jpg?resize=600%2C900',
      duration: 30,
      ingredients: [
        'White and Green Asparagus',
        '30g Pine Nuts',
        '300g Cherry Tomatoes',
        'Salad',
        'Salt, Pepper and Olive Oil'
      ],
      steps: [
        'Wash, peel and cut the asparagus',
        'Cook in salted water',
        'Salt and pepper the asparagus',
        'Roast the pine nuts',
        'Halve the tomatoes',
        'Mix with asparagus, salad and dressing',
        'Serve with Baguette'
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm2',
      categories: [
        'c3',
      ],
      title: 'Lemon or Ginger chicken',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSONv3s52_NL76V8DzlI5PLLOea5UrSZ0IGhQ&usqp=CAU',
      duration: 30,
      ingredients: [
        'White and Green Asparagus',
        '30g Pine Nuts',
        '300g Cherry Tomatoes',
        'Salad',
        'Salt, Pepper and Olive Oil'
      ],
      steps: [
        'Wash, peel and cut the asparagus',
        'Cook in salted water',
        'Salt and pepper the asparagus',
        'Roast the pine nuts',
        'Halve the tomatoes',
        'Mix with asparagus, salad and dressing',
        'Serve with Baguette'
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm3',
      categories: [
        'c3',
      ],
      title: 'Chicken Chow Mein',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzXrOGkF_ukZb6nL2KK1Qrs0uH7aREAbuq3Q&usqp=CAU',
      duration: 30,
      ingredients: [
        'White and Green Asparagus',
        '30g Pine Nuts',
        '300g Cherry Tomatoes',
        'Salad',
        'Salt, Pepper and Olive Oil'
      ],
      steps: [
        'Wash, peel and cut the asparagus',
        'Cook in salted water',
        'Salt and pepper the asparagus',
        'Roast the pine nuts',
        'Halve the tomatoes',
        'Mix with asparagus, salad and dressing',
        'Serve with Baguette'
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm4',
      categories: [
        'c3',
      ],
      title: 'Chinese Chicken Badam',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://www.yourhomebasedmom.com/wp-content/uploads/2020/01/almond-chicken-2-1.jpg',
      duration: 30,
      ingredients: [
        'White and Green Asparagus',
        '30g Pine Nuts',
        '300g Cherry Tomatoes',
        'Salad',
        'Salt, Pepper and Olive Oil'
      ],
      steps: [
        'Wash, peel and cut the asparagus',
        'Cook in salted water',
        'Salt and pepper the asparagus',
        'Roast the pine nuts',
        'Halve the tomatoes',
        'Mix with asparagus, salad and dressing',
        'Serve with Baguette'
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm5',
      categories: [
        'c3',
      ],
      title: 'Murag Makai',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl: 'https://i.ytimg.com/vi/wSEWxVUJo6k/hqdefault.jpg',
      duration: 30,
      ingredients: [
        'White and Green Asparagus',
        '30g Pine Nuts',
        '300g Cherry Tomatoes',
        'Salad',
        'Salt, Pepper and Olive Oil'
      ],
      steps: [
        'Wash, peel and cut the asparagus',
        'Cook in salted water',
        'Salt and pepper the asparagus',
        'Roast the pine nuts',
        'Halve the tomatoes',
        'Mix with asparagus, salad and dressing',
        'Serve with Baguette'
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm6',
      categories: [
        'c3',
      ],
      title: 'White Chicken Karahi',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl: 'https://i.ytimg.com/vi/ebDXpa-8JcA/maxresdefault.jpg',
      duration: 30,
      ingredients: [
        'White and Green Asparagus',
        '30g Pine Nuts',
        '300g Cherry Tomatoes',
        'Salad',
        'Salt, Pepper and Olive Oil'
      ],
      steps: [
        'Wash, peel and cut the asparagus',
        'Cook in salted water',
        'Salt and pepper the asparagus',
        'Roast the pine nuts',
        'Halve the tomatoes',
        'Mix with asparagus, salad and dressing',
        'Serve with Baguette'
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm7',
      categories: [
        'c3',
      ],
      title: 'Chicken Chaap',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://3.bp.blogspot.com/-E8hqp6cysoQ/UOtDFFNq6fI/AAAAAAAAGpo/lymu33wrWxo/s1600/Chicken+Chaap.01.jpg',
      duration: 30,
      ingredients: [
        'White and Green Asparagus',
        '30g Pine Nuts',
        '300g Cherry Tomatoes',
        'Salad',
        'Salt, Pepper and Olive Oil'
      ],
      steps: [
        'Wash, peel and cut the asparagus',
        'Cook in salted water',
        'Salt and pepper the asparagus',
        'Roast the pine nuts',
        'Halve the tomatoes',
        'Mix with asparagus, salad and dressing',
        'Serve with Baguette'
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm8',
      categories: [
        'c3',
      ],
      title: 'Chinese Fried chicken ',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://i.ndtvimg.com/i/2018-01/fried-chicken_696x400_51514877919.jpg',
      duration: 30,
      ingredients: [
        '8 Chicken drumsticks/breast',
        '100 ml curd',
        '1 Egg (beaten)',
        '50 gms all purpose flour',
        '50 gms bread crumbs',
        '1 tsp chilli powder',
        '1 tsp White Pepper Powder ',
        '1 tsp onion (dried), powdered',
        '1 tsp basil/tulsi leaves (dried), powdered',
        '1 tsp oregano / omam leaves (dried), powdered',
        '1 green chilli, chopped',
        '1 tsp garlic (dried)',
        "1 tsp ginger (dried)",
      ],
      steps: [
        'Wash and clean chicken. Drain water well from chicken',
        'Add beaten egg, curd, 1/2 tsp chilli powder, salt to chicken and mix well. Marinate it for at least 3 to 4 hours.',
        'Mix all purpose flour, green chillies, white pepper, oregano, garlic, ginger, basil or tulsi leaves, remaining chilli powder and salt.',
        'Cover marinated chicken with spicy all purpose flour mix and then with bread crumbs.',
        'Heat oil in a thick bottom kadai and deep fry the chicken in a slow fire till it is cooked',
        'Serve hot with tomato ketchup',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm9',
      categories: [
        'c3',
      ],
      title: 'Tawa chicken karahi ',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl: 'https://i.ytimg.com/vi/YyWu-TagfGs/maxresdefault.jpg',
      duration: 30,
      ingredients: [
        '1 whole chicken',
        '250 gm yogurt dried',
        '1 cup oil',
        '1/2 cup fresh coriander leaves chopped',
        '8 green chilies chopped',
        '2 tbsp ginger garlic paste',
        '2 tbsp red chili crushed',
        '1 tsp cumin seeds roasted ,& crushed',
        '1 tsp all spice powder',
        'salt to taste',
        'green coriander for garnishing',
      ],
      steps: [
        ' Cut whole chicken from the center but it should be remain in 1 piece.',
        'Set aside.',
        'In a small bowl, mix together all spices with yogurt',
        'Then apply this mixture on the chicken pieces',
        'Heat oil on a big tawa (griddle)',
        'Place chicken on it and cook on low flame for 10 minutes',
        'Covered and cook another 15 minutes or until chicken is tender and all water dries up',
        'Take it out in a serving dish',
        'Top with green coriander leaves',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm10',
      categories: [
        'c3',
      ],
      title: 'Greek Chicken Karahi',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://www.foodiecrush.com/wp-content/uploads/2018/06/Grilled-Greek-Chicken-foodiecrush.com-014-300x300-1-300x270.jpg',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),

    //  Pasta
    Meal(
      id: 'm1',
      categories: [
        'c4',
      ],
      title: 'Macaroni',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://www.whiskaffair.com/wp-content/uploads/2014/07/Masala-Macaroni-4.jpg',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm2',
      categories: [
        'c4',
      ],
      title: 'Farfalle',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl: 'https://i.ytimg.com/vi/DADm949zFVk/maxresdefault.jpg',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm3',
      categories: [
        'c4',
      ],
      title: 'Farfalle',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://www.thespruceeats.com/thmb/q4E3mki6mqsDOLNSaLSVQ4UCfw0=/4559x3039/filters:fill(auto,1)/cappelletti-little-hats-of-filled-pasta-4054301-hero-01-e583c8a4cada4b21ababeb6175c34d31.jpg',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm4',
      categories: [
        'c4',
      ],
      title: 'Spätzle',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://frenchgirlcuisine.com/wp-content/uploads/homemade-german-kaese-spaetzle-recipe.jpg',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm5',
      categories: [
        'c4',
      ],
      title: 'Vermicelli ',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://c.ndtvimg.com/2019-09/gpu94eo8_upma_625x300_17_September_19.jpg',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm6',
      categories: [
        'c4',
      ],
      title: 'Ptitim ',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://silkroadrecipes.com/wp-content/uploads/2020/08/Ptitim-Israeli-Couscous-Salad-square.jpg',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm7',
      categories: [
        'c4',
      ],
      title: 'Cannelloni',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://i.pinimg.com/originals/7d/9e/f4/7d9ef4ab3ae046e2e4569c29fb45f4b5.jpg',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),

    // Pizza
    Meal(
      id: 'm1',
      categories: [
        'c5',
      ],
      title: 'Neapolitan Pizza',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://cdnimg.webstaurantstore.com/uploads/buying_guide/2014/11/pizzatypes-margherita-.jpg',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm2',
      categories: [
        'c5',
      ],
      title: 'Chicago pizza',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://cdnimg.webstaurantstore.com/uploads/buying_guide/2014/11/pizzatypes-deepdish.jpg',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm3',
      categories: [
        'c5',
      ],
      title: 'New York-Style Pizza',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://cdnimg.webstaurantstore.com/uploads/blog/2016/8/flat.jpg',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm4',
      categories: [
        'c5',
      ],
      title: 'Sicilian Pizza',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://cdnimg.webstaurantstore.com/uploads/blog/2016/8/rectangle.jpg',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm5',
      categories: [
        'c5',
      ],
      title: 'Greek Pizza',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://cdnimg.webstaurantstore.com/uploads/blog/2016/8/onions.jpg',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm6',
      categories: [
        'c5',
      ],
      title: ' California Pizza',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://cdnimg.webstaurantstore.com/uploads/buying_guide/2014/11/pizzatypes-gourmet.jpg',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm7',
      categories: [
        'c5',
      ],
      title: ' St. Louis Pizza',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://cdnimg.webstaurantstore.com/uploads/blog/2019/3/blog-types-pizza_in-blog-8.jpg',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm8',
      categories: [
        'c5',
      ],
      title: ' California Pizza',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://cdnimg.webstaurantstore.com/uploads/buying_guide/2014/11/pizzatypes-gourmet.jpg',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm9',
      categories: [
        'c5',
      ],
      title: ' Fajita',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://ashleemarie.com/wp-content/uploads/2016/02/chicken-fajita-pizza.jpg',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm10',
      categories: [
        'c5',
      ],
      title: ' kabab crust pizza',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl: 'https://i.redd.it/8bx6viviaq851.jpg',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm11',
      categories: [
        'c5',
      ],
      title: 'Cheese Pizza',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://static.toiimg.com/thumb/53110049.cms?width=1200&height=900',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm12',
      categories: [
        'c5',
      ],
      title: ' BBQ Chicken Pizza',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://www.diabetesfoodhub.org/system/thumbs/system/images/recipes/Recid_76_BBQ_Chicken_Pizza_iStock-484653761_02262018_2959761669.jpg',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm1',
      categories: [
        'c6',
      ],
      title: 'Red Beans SPAM',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2020%2F03%2F6277719-2000.jpg&w=272&h=272&c=sc&poi=%5B1000%2C932%5D&q=85',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm2',
      categories: [
        'c6',
      ],
      title: 'Pacific Cuban Black ',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F1127174.jpg&w=272&h=272&c=sc&poi=face&q=85',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm3',
      categories: [
        'c6',
      ],
      title: 'Italian-Style Vegetarian',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://cdn.cheapism.com/images/iStock-478854621.max-784x410.jpg',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm4',
      categories: [
        'c6',
      ],
      title: 'Asian-Style Fried',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://cdn.cheapism.com/images/iStock-1191267023.max-784x410.jpg',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm5',
      categories: [
        'c6',
      ],
      title: 'African Rice and Beans',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://cdn.cheapism.com/images/iStock-538335761.max-784x410.jpg',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm6',
      categories: [
        'c6',
      ],
      title: 'South Louisiana White',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://cdn.cheapism.com/images/iStock-1085325338_1.max-784x410.jpg',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm7',
      categories: [
        'c6',
      ],
      title: 'Spanish Chicken and Rice',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://cdn.cheapism.com/images/iStock-481018142.max-784x410.jpg',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm8',
      categories: [
        'c6',
      ],
      title: 'Mexican Beef N Rice Skillet',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://cdn.cheapism.com/images/iStock-517537850.max-784x410.png',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),

    // Soup
    Meal(
      id: 'm1',
      categories: [
        'c8',
      ],
      title: 'Minestrone Soup',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://www.tasteofhome.com/wp-content/uploads/2017/09/Contest-Winning-Easy-Minestrone_exps119788_FM143298B03_11_2bC_RMS.jpg?w=1200',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm2',
      categories: [
        'c8',
      ],
      title: 'Chicken Noodle Soup',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://www.tasteofhome.com/wp-content/uploads/2017/09/exps192832_TH163619D09_30_2b.jpg?w=1200',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm3',
      categories: [
        'c8',
      ],
      title: 'Italian Wedding Soup',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://www.tasteofhome.com/wp-content/uploads/2017/09/exps179731_TH143193A04_30_4b.jpg?w=1200',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
      id: 'm4',
      categories: [
        'c8',
      ],
      title: 'Tomato Soup',
      affordability: Affordability.Luxurious,
      complexity: Complexity.Simple,
      imageUrl:
          'https://www.tasteofhome.com/wp-content/uploads/2018/07/The-Best-Ever-Tomato-Soup_EXPS_THSO18_222724_D03_06_5b.jpg?w=1200',
      duration: 30,
      ingredients: [
        '1 pound boneless skinless chicken breasts (about 2 large breasts)',
        '⅓ cup plain Greek yogurt',
        '¼ cup olive oil',
        '4 lemons',
        '4-5 cloves garlic pressed or minced',
        '2 tablespoons dried oregano',
        '1 teaspoon kosher salt',
        '½ teaspoon freshly ground black pepper',
      ],
      steps: [
        'Place the chicken pieces in a freezer bag or a bowl and set aside.',
        'Add the Greek yogurt and olive oil to a medium size bowl. Zest one of the lemons and add to the bowl. Juice that lemon into the bowl with the zest. Slice the other three lemons and set aside. Add the minced garlic, oregano, kosher salt and black pepper to the lemon juice and zest and stir. Pour half of the marinade into the freezer bag or the bowl with the chicken pieces and reserve the other half of the marinade for basting. Marinate the chicken for 30 minutes or up to 3 hours in the refrigerator',
        'When ready to grill, prepare the grill by lightly oiling the grate with vegetable oil or cooking spray and set to medium high heat',
        'Grill the chicken, basting with the reserved marinade and turning often so each side browns and has light grill marks, until cooked through, about 15-20 minutes or until the chicken juices run clear. During the last 5 minutes of cooking add the 3 sliced lemons to the grill, turning once or twice. Allow the chicken to rest for 5 minutes before slicing and serve with the grilled lemons. Refrigerate leftovers for up to 3 days',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
  ];
  List<Meal> get item1 {
    return [..._items];
  }

  void addValue() {
    // item.add(value);
    notifyListeners();
  }

  List<Meal> findViewById(String id) {
    return item1.where((element) => element.categories.contains(id)).toList();
  }
}
